# Generated by Django 5.0.6 on 2024-05-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('dogowner', 'Dog Owner'), ('dogwalker', 'Dog Walker')], max_length=50, unique=True),
        ),
    ]
