# Generated by Django 5.0.6 on 2024-05-30 10:53

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.create(name='dogowner')
    Role.objects.create(name='dogwalker')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]

